In [1]:
import numpy as np
import pandas as pd

### Q1. Pandas Version

In [2]:
pd.__version__

'2.2.3'

### Q2. Records count

In [5]:
df = pd.read_csv('./laptops.csv')
df.shape[0]

2160

### Q3. Laptop brands

In [9]:
df['Brand'].unique().shape[0]

27

### Q4. Missing values

In [21]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

### Q5. Maximum final price

In [30]:
df[df['Brand'] == 'Dell']['Final Price'].max()

np.float64(3936.0)

### Q6. Median value of Screen

1. Find the median value of Screen column in the dataset.

In [32]:
df['Screen'].median()

np.float64(15.6)


2. Next, calculate the most frequent value of the same Screen column.

In [33]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64


3. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

4. Now, calculate the median value of Screen once again.

In [35]:
df['Screen'].fillna(df['Screen'].mode()).median()

np.float64(15.6)

### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.

In [50]:
df[df['Brand'] == 'Innjoo']

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

2. Select only columns RAM, Storage, Screen.

In [49]:
df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

3. Get the underlying NumPy array. Let's call it X.

In [71]:
X = np.array(df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']])
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.=

In [64]:
XTX = np.matmul(np.transpose(X), X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

5. Compute the inverse of XTX.

In [65]:
np.linalg.inv(XTX)

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

6. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

In [67]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [100]:
w = np.linalg.matmul(np.linalg.matmul(np.linalg.inv(XTX), np.transpose(X)), y)
w

array([45.58076606,  0.42783519, 45.29127938])

8. What's the sum of all the elements of the result?

In [101]:
w.sum()

np.float64(91.2998806299555)